title: "T6970 - GitHub.io"
description: ""
url: "https://username.github.io"
baseurl: ""

author:
  name: "T6970"

markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

collections:
  app:
    output: true
    permalink: /app/:name/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: "T6970"
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: "_app"
      type: app
    values:
      layout: default
